apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-zabbtix
spec:
  selector:
    matchLabels:
      app: monitor-zabbtix
  template:
    metadata:
      labels:
        app: monitor-zabbtix
    spec:
      containers:
        - name: monitor-zabbtix
          image: app
