apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

namespace: monitor-zabbtix
images:
  - name: app
    newName: athaydaooo/monitor-zabbtix
    newTag: latest
